
TARGET   = lib/PortAudio.a

SOURCES  = src/src/common/pa_allocation.c \
           src/src/common/pa_converters.c \
           src/src/common/pa_cpuload.c \
           src/src/common/pa_debugprint.c \
           src/src/common/pa_dither.c \
           src/src/common/pa_front.c \
           src/src/common/pa_process.c \
           src/src/common/pa_ringbuffer.c \
           src/src/common/pa_skeleton.c \
           src/src/common/pa_stream.c \
           src/src/common/pa_trace.c \
           src/src/hostapi/wmme/pa_win_wmme.c \
           src/src/os/win/pa_win_hostapis.c \
           src/src/os/win/pa_win_util.c \
           src/src/os/win/pa_win_waveformat.c

OBJECTS  = $(SOURCES:.c=.o)

CXX      = gcc
AR       = ar
CXXFLAGS = -Wall -O6 -fomit-frame-pointer \
           -DPA_NO_DS \
           -DPA_NO_ASIO
INCLUDE  = -I src/include \
           -I src/src/common \
           -I src/src/hostapi/wmme \
           -I src/os/win

all: $(TARGET)

$(TARGET): $(OBJECTS)
	$(AR) cru $(TARGET) $(OBJECTS)
	cp src/include/*.h include

.c.o:
	$(CXX) $(CXXFLAGS) $(INCLUDE) -o $(<:.c=.o) -c $<

clean:
	rm -f $(OBJECTS) $(TARGET)
