
TARGET   = lib/Julius.a

SOURCES  = src/libjulius/src/adin-cut.c \
           src/libjulius/src/backtrellis.c \
           src/libjulius/src/beam.c \
           src/libjulius/src/callback.c \
           src/libjulius/src/confnet.c \
           src/libjulius/src/default.c \
           src/libjulius/src/dfa_decode.c \
           src/libjulius/src/factoring_sub.c \
           src/libjulius/src/gmm.c \
           src/libjulius/src/gramlist.c \
           src/libjulius/src/graphout.c \
           src/libjulius/src/hmm_check.c \
           src/libjulius/src/instance.c \
           src/libjulius/src/jfunc.c \
           src/libjulius/src/m_adin.c \
           src/libjulius/src/m_chkparam.c \
           src/libjulius/src/m_fusion.c \
           src/libjulius/src/m_info.c \
           src/libjulius/src/m_jconf.c \
           src/libjulius/src/m_options.c \
           src/libjulius/src/m_usage.c \
           src/libjulius/src/multi-gram.c \
           src/libjulius/src/ngram_decode.c \
           src/libjulius/src/outprob_style.c \
           src/libjulius/src/pass1.c \
           src/libjulius/src/plugin.c \
           src/libjulius/src/realtime-1stpass.c \
           src/libjulius/src/recogmain.c \
           src/libjulius/src/search_bestfirst_main.c \
           src/libjulius/src/search_bestfirst_v1.c \
           src/libjulius/src/search_bestfirst_v2.c \
           src/libjulius/src/spsegment.c \
           src/libjulius/src/useropt.c \
           src/libjulius/src/wav2mfcc.c \
           src/libjulius/src/wchmm.c \
           src/libjulius/src/wchmm_check.c \
           src/libjulius/src/word_align.c \
           src/libsent/src/adin/adin_file.c \
           src/libsent/src/adin/adin_portaudio.c \
           src/libsent/src/adin/adin_tcpip.c \
           src/libsent/src/adin/ds48to16.c \
           src/libsent/src/adin/zc-e.c \
           src/libsent/src/adin/zmean.c \
           src/libsent/src/anlz/param_malloc.c \
           src/libsent/src/anlz/paramselect.c \
           src/libsent/src/anlz/paramtypes.c \
           src/libsent/src/anlz/rdparam.c \
           src/libsent/src/anlz/strip.c \
           src/libsent/src/anlz/strip_mfcc.c \
           src/libsent/src/anlz/wrsamp.c \
           src/libsent/src/anlz/wrwav.c \
           src/libsent/src/dfa/cpair.c \
           src/libsent/src/dfa/dfa_lookup.c \
           src/libsent/src/dfa/dfa_malloc.c \
           src/libsent/src/dfa/dfa_util.c \
           src/libsent/src/dfa/init_dfa.c \
           src/libsent/src/dfa/mkcpair.c \
           src/libsent/src/dfa/mkterminfo.c \
           src/libsent/src/dfa/rddfa.c \
           src/libsent/src/hmminfo/cdhmm.c \
           src/libsent/src/hmminfo/cdset.c \
           src/libsent/src/hmminfo/check_hmm_restriction.c \
           src/libsent/src/hmminfo/check_hmmtype.c \
           src/libsent/src/hmminfo/chkhmmlist.c \
           src/libsent/src/hmminfo/guess_cdHMM.c \
           src/libsent/src/hmminfo/hmm_lookup.c \
           src/libsent/src/hmminfo/init_phmm.c \
           src/libsent/src/hmminfo/put_htkdata_info.c \
           src/libsent/src/hmminfo/rdhmmdef.c \
           src/libsent/src/hmminfo/rdhmmdef_data.c \
           src/libsent/src/hmminfo/rdhmmdef_dens.c \
           src/libsent/src/hmminfo/rdhmmdef_mpdf.c \
           src/libsent/src/hmminfo/rdhmmdef_options.c \
           src/libsent/src/hmminfo/rdhmmdef_regtree.c \
           src/libsent/src/hmminfo/rdhmmdef_state.c \
           src/libsent/src/hmminfo/rdhmmdef_streamweight.c \
           src/libsent/src/hmminfo/rdhmmdef_tiedmix.c \
           src/libsent/src/hmminfo/rdhmmdef_trans.c \
           src/libsent/src/hmminfo/rdhmmdef_var.c \
           src/libsent/src/hmminfo/rdhmmlist.c \
           src/libsent/src/hmminfo/read_binhmm.c \
           src/libsent/src/hmminfo/read_binhmmlist.c \
           src/libsent/src/hmminfo/write_binhmm.c \
           src/libsent/src/hmminfo/write_binhmmlist.c \
           src/libsent/src/net/rdwt.c \
           src/libsent/src/net/server-client.c \
           src/libsent/src/ngram/init_ngram.c \
           src/libsent/src/ngram/ngram_access.c \
           src/libsent/src/ngram/ngram_compact_context.c \
           src/libsent/src/ngram/ngram_lookup.c \
           src/libsent/src/ngram/ngram_malloc.c \
           src/libsent/src/ngram/ngram_read_arpa.c \
           src/libsent/src/ngram/ngram_read_bin.c \
           src/libsent/src/ngram/ngram_util.c \
           src/libsent/src/ngram/ngram_write_bin.c \
           src/libsent/src/phmm/addlog.c \
           src/libsent/src/phmm/calc_mix.c \
           src/libsent/src/phmm/calc_tied_mix.c \
           src/libsent/src/phmm/gms.c \
           src/libsent/src/phmm/gms_gprune.c \
           src/libsent/src/phmm/gprune_beam.c \
           src/libsent/src/phmm/gprune_common.c \
           src/libsent/src/phmm/gprune_heu.c \
           src/libsent/src/phmm/gprune_none.c \
           src/libsent/src/phmm/gprune_safe.c \
           src/libsent/src/phmm/mkwhmm.c \
           src/libsent/src/phmm/outprob.c \
           src/libsent/src/phmm/outprob_init.c \
           src/libsent/src/phmm/vsegment.c \
           src/libsent/src/util/aptree.c \
           src/libsent/src/util/confout.c \
           src/libsent/src/util/endian.c \
           src/libsent/src/util/gzfile.c \
           src/libsent/src/util/jlog.c \
           src/libsent/src/util/mybmalloc.c \
           src/libsent/src/util/mymalloc.c \
           src/libsent/src/util/mystrtok.c \
           src/libsent/src/util/ptree.c \
           src/libsent/src/util/qsort.c \
           src/libsent/src/util/readfile.c \
           src/libsent/src/util/strcasecmp.c \
           src/libsent/src/voca/init_voca.c \
           src/libsent/src/voca/voca_load_htkdict.c \
           src/libsent/src/voca/voca_load_wordlist.c \
           src/libsent/src/voca/voca_lookup.c \
           src/libsent/src/voca/voca_malloc.c \
           src/libsent/src/voca/voca_util.c \
           src/libsent/src/wav2mfcc/mfcc-core.c \
           src/libsent/src/wav2mfcc/para.c \
           src/libsent/src/wav2mfcc/ss.c \
           src/libsent/src/wav2mfcc/wav2mfcc-buffer.c \
           src/libsent/src/wav2mfcc/wav2mfcc-pipe.c \
           src/msvc/config/version.c

OBJECTS  = $(SOURCES:.c=.o)

CXX      = gcc
AR       = ar
CXXFLAGS = -Wall -O6 -fomit-frame-pointer \
           -DHAVE_ZLIB
INCLUDE  = -I src/libjulius/include \
           -I src/libsent/include \
           -I ../Library_PortAudio/include \
           -I ../Library_zlib/include

all: src/libjulius/include/julius/config.h src/libsent/include/sent/config.h $(TARGET)

$(TARGET): $(OBJECTS)
	@mkdir -p $(@D)
	$(AR) cru $(TARGET) $(OBJECTS)
	cp src/libjulius/include/julius/*.h include/julius
	cp src/libsent/include/sent/*.h include/sent

.c.o:
	$(CXX) $(CXXFLAGS) $(INCLUDE) -o $(<:.c=.o) -c $<

clean:
	rm -f src/libjulius/include/julius/config.h src/libsent/include/sent/config.h $(OBJECTS) $(TARGET)

src/libjulius/include/julius/config.h:
	cd src/libjulius; chmod +x ./configure; ./configure --disable-plugin; cd ../..;

src/libsent/include/sent/config.h:
	cd src/libsent; chmod +x ./configure; ./configure --with-mictype=libportaudio; cd ../..;
