
TARGET   = ../Release/Plugins/Plugin_Open_JTalk.so

SOURCES  = Open_JTalk.cpp \
           Open_JTalk_Manager.cpp \
           Open_JTalk_Thread.cpp \
           Plugin_Open_JTalk.cpp

OBJECTS  = $(SOURCES:.cpp=.o)

LDADD    = ../Library_MMDAgent/lib/MMDAgent.a \
           ../Library_MMDFiles/lib/MMDFiles.a \
           ../Library_GLFW/lib/GLFW.a \
           ../Library_GLee/lib/GLee.a \
           ../Library_Bullet_Physics/lib/Bullet_Physics.a \
           ../Library_libpng/lib/libpng.a \
           ../Library_JPEG/lib/JPEG.a \
           ../Library_zlib/lib/zlib.a \
           ../Library_hts_engine_API/lib/hts_engine_API.a \
           ../Library_Open_JTalk/lib/Open_JTalk.a \
           ../Library_PortAudio/lib/PortAudio.a

CXX      = gcc
AR       = ar
CXXFLAGS = -Wall -O6 -fomit-frame-pointer \
           -shared \
           -DMMDAGENT \
           -DAUDIO_PLAY_PORTAUDIO
INCLUDE  = -I ../Library_Bullet_Physics/include \
           -I ../Library_GLee/include \
           -I ../Library_GLFW/include \
           -I ../Library_MMDFiles/include \
           -I ../Library_MMDAgent/include \
           -I ../Library_hts_engine_API/include \
           -I ../Library_Open_JTalk/include \
           -I ../Library_PortAudio/include

all: $(TARGET)

$(TARGET): $(OBJECTS) $(LDADD)
	$(CXX) $(CXXFLAGS) $(OBJECTS) $(LDADD) -o $(TARGET) \
	-lGLU -lGL -lX11 -lasound -ldl -lrt -lm -lpthread

.cpp.o:
	$(CXX) $(CXXFLAGS) $(INCLUDE) -o $(<:.cpp=.o) -c $<

clean:
	rm -f $(OBJECTS) $(TARGET)
